### ISSUE TITLE
Export as MarkDown option

### ISSUE THREAD

**Issue by mikej888** [akrause2014/webtimex#4]
Useful for e-mails e.g.
- Project One : 12:34
- Project Two : 23:10

**Comment by akrause2014** [comment]
Would that be useful displayed as part of the web page, in "pre" tags, to copy & paste into an email? Or download as text file? Both?

**Comment by mikej888** [comment]
Like the Export as JSON option - shown on screen then, optionally, downloadable via a button.

**Comment by akrause2014** [comment]
Added JSON and text option. User selects from HTML, Text or JSON display in the report page and can download as JSON or text file as well.
